name: "pypi"

on:
  release:
    types: [released]
  workflow_dispatch: # manual trigger

jobs:
  # Adapted from pydantic/pydantic-core
  build:
    name: build on ${{ matrix.platform.os }} / ${{ matrix.interpreter }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            { os: linux, runs-on: ubuntu-latest },
            { os: linux_aarch64, runs-on: ubuntu-24.04-arm },
            { os: windows, runs-on: windows-latest },
            { os: macos, runs-on: macos-latest },
          ]
        interpreter: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.14t"]
        target: [x86_64, aarch64]

        exclude:
          - platform:
              os: linux_aarch64
            target: x86_64
          - platform:
              os: linux
            target: aarch64
          - platform:
              os: windows
            target: aarch64
          - platform:
              os: macos
            target: x86_64 # too slow on GitHub runners

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.interpreter }}

      - name: Install Rust stable
        id: rust-toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: llvm-tools
          toolchain: stable

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          target: ${{ matrix.target }}
          args: >
            --release
            --features python
            --interpreter ${{ matrix.interpreter }}
          rust-toolchain: ${{ steps.rust-toolchain.outputs.name }}
          docker-options: -e CI

      - run: ${{ (matrix.os == 'windows' && 'dir') || 'ls -lh' }} target/wheels/

      - uses: actions/upload-artifact@v5
        with:
          name: pypi_files_${{ matrix.os }}_${{ matrix.target }}_${{ matrix.interpreter }}
          path: target/wheels

  publish:
    name: publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: get dist artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: pypi_files_*
          merge-multiple: true
          path: target/wheels

      - name: Publish
        run: uv publish --trusted-publishing always
